import type { Project } from "./types";
import { productImages } from "./product-images";

// Portfolio grouped by ICP + packaging type (blueprint §12). Each project shows
// ALL photographed angles of that product via a left–right scrolling gallery.
//
// Products are named by what they are, not by the client on the box. The photos
// carry real client artwork; until a client confirms they're happy to be credited,
// `client` stays a generic descriptor and no brand is named in copy.

const img = (slug: string) => productImages[slug] ?? [];

export const projects: Project[] = [
  // ── Gift / corporate ──────────────────────────────────────────────
  {
    slug: "corporate-gift-box",
    client: "Fragrance brand",
    clientType: "Brand Gifting",
    industry: "Gift",
    packagingType: "Gift Boxes",
    filters: ["Gift", "Gift Boxes", "Boxes", "Cosmetics"],
    product: "Corporate gift box",
    material: "Rigid board, magnetic closure",
    customization: ["Rigid magnetic box", "Full-bleed printed interior", "Fitted insert", "Soft-touch finish"],
    quantityRange: "300–500",
    problemSolved: "Wanted a gift box that holds a fragrance, a candle and a card without them moving in transit.",
    outcome: "Magnetic rigid box with a printed interior and fitted insert, shot from twelve angles.",
    images: img("corporate-gift-box"),
    featured: true,
  },
  {
    slug: "discovery-box",
    client: "Fragrance brand",
    clientType: "Discovery / Sampling",
    industry: "Gift",
    packagingType: "Gift Boxes",
    filters: ["Gift", "Gift Boxes", "Cosmetics"],
    product: "Discovery box",
    material: "Printed rigid board",
    customization: ["Printed box", "Vial insert", "Wraparound type"],
    quantityRange: "500–1,000",
    problemSolved: "Needed a compact sampler that presents six scent vials for a discovery campaign.",
    outcome: "Slim sampler box that holds the full range and reads as a gift on arrival.",
    images: img("discovery-box"),
  },
  {
    slug: "welcome-kit",
    client: "Home appliance brand",
    clientType: "Corporate Gifting",
    industry: "Gift",
    packagingType: "Inserts & Cards",
    filters: ["Gift", "Inserts & Cards", "Gift Boxes", "Boxes"],
    product: "Welcome kit",
    material: "Rigid board, magnetic closure",
    customization: ["Rigid magnetic box", "Foil edge", "Die-cut foam insert", "Matching notebook & pen"],
    quantityRange: "500–1,000",
    problemSolved: "Onboarding gifts arrived as loose items with no sense of occasion.",
    outcome: "A magnetic rigid box with a seated insert holding a flask, notebook and pen — one clean reveal.",
    images: img("welcome-kit"),
    featured: true,
  },

  // ── Cosmetics / fragrance ─────────────────────────────────────────
  {
    slug: "mist-boomerang-chic",
    client: "Fragrance brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Boomerang Chic",
    material: "Printed board",
    customization: ["Printed box", "Brand-colour design"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed eye-catching retail boxes for a 150ml body-mist line.",
    outcome: "Bold printed mist box photographed from four angles.",
    images: img("mist-boomerang-chic"),
    featured: true,
  },
  {
    slug: "mist-blank-spell",
    client: "Fragrance brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Blank Spell",
    material: "Printed board",
    customization: ["Printed box", "Matte lamination"],
    quantityRange: "1,000–5,000",
    problemSolved: "Wanted a premium feel across a mist range.",
    outcome: "Clean printed box consistent with the range.",
    images: img("mist-blank-spell"),
  },
  {
    slug: "mist-classical-rockstar",
    client: "Fragrance brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Classical Rockstar",
    material: "Printed board",
    customization: ["Printed box", "Brand-colour design"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed shelf stand-out for a mist SKU.",
    outcome: "Distinct printed box shot from multiple angles.",
    images: img("mist-classical-rockstar"),
  },
  {
    slug: "mist-crooked-smile",
    client: "Fragrance brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Crooked Smile",
    material: "Printed board",
    customization: ["Printed box", "Spot finish"],
    quantityRange: "1,000–5,000",
    problemSolved: "Wanted a playful, on-brand box.",
    outcome: "Characterful printed box across three views.",
    images: img("mist-crooked-smile"),
  },
  {
    slug: "mist-designer-crime",
    client: "Fragrance brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Designer Crime",
    material: "Printed board",
    customization: ["Printed box"],
    quantityRange: "500–1,000",
    problemSolved: "Needed a cohesive box for a new scent.",
    outcome: "On-brand printed box, two angles.",
    images: img("mist-designer-crime"),
  },
  {
    slug: "mist-drop-beat",
    client: "Fragrance brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Drop Beat",
    material: "Printed board",
    customization: ["Printed box", "Brand-colour design"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed a vibrant box for a youth-oriented scent.",
    outcome: "Energetic printed box across three views.",
    images: img("mist-drop-beat"),
  },
  {
    slug: "perfume-kai",
    client: "Fragrance brand",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Perfume box — Kai",
    material: "Printed board",
    customization: ["Printed box", "Curved-top structure"],
    quantityRange: "300–500",
    problemSolved: "Needed shelf presence for a 100ml eau de parfum.",
    outcome: "Printed perfume box with box-and-bottle shots.",
    images: img("perfume-kai"),
    featured: true,
  },
  {
    slug: "perfume-mulan",
    client: "Fragrance brand",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Perfume box — Mulan",
    material: "Printed board",
    customization: ["Printed box", "Brand-colour design"],
    quantityRange: "300–500",
    problemSolved: "Wanted a distinct box within a shared range structure.",
    outcome: "Printed perfume box, multiple views.",
    images: img("perfume-mulan"),
  },
  {
    slug: "perfume-diyar",
    client: "Fragrance brand",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Perfume box — Diyar",
    material: "Printed board",
    customization: ["Printed box"],
    quantityRange: "300–500",
    problemSolved: "Needed a box for a new scent that still reads as part of the range.",
    outcome: "Clean printed perfume box.",
    images: img("perfume-diyar"),
  },
  {
    slug: "perfume-ezra",
    client: "Fragrance brand",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Perfume box — Ezra",
    material: "Printed board",
    customization: ["Printed box"],
    quantityRange: "300–500",
    problemSolved: "Wanted consistent packaging across scents.",
    outcome: "Printed perfume box matched to the range.",
    images: img("perfume-ezra"),
  },
  {
    slug: "perfume-mumba",
    client: "Fragrance brand",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Perfume box — Mumba",
    material: "Printed board",
    customization: ["Printed box", "Curved-top structure", "Brand-colour design"],
    quantityRange: "300–500",
    problemSolved: "Needed a standout box for a hero scent.",
    outcome: "Bold printed perfume box, shot in studio and on white.",
    images: img("perfume-mumba"),
  },
  {
    slug: "perfume-zaram",
    client: "Fragrance brand",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Perfume box — Zaram",
    material: "Printed board",
    customization: ["Printed box"],
    quantityRange: "300–500",
    problemSolved: "Wanted a refined box for a fragrance launch.",
    outcome: "Refined printed perfume box.",
    images: img("perfume-zaram"),
  },
  {
    slug: "serum-box",
    client: "Skincare brand",
    clientType: "Skincare",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Serum box",
    material: "Printed board",
    customization: ["Printed box", "Tall narrow structure"],
    quantityRange: "500–1,000",
    problemSolved: "Needed a slim carton for a 30ml dropper bottle that still carries the claims copy.",
    outcome: "Tall printed carton with room for ingredient and claims text down the panel.",
    images: img("serum-box"),
  },
  {
    slug: "essential-oil-boxes",
    client: "Essential oil brand",
    clientType: "Aromatherapy",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes", "Retail"],
    product: "Essential oil boxes",
    material: "Printed board",
    customization: ["Printed boxes", "Colour-coded range", "Regulatory panel"],
    quantityRange: "1,000–5,000",
    problemSolved: "A growing range of 10ml oils needed boxes that stay recognisable but read apart on shelf.",
    outcome: "One structure, colour-coded per scent, with the dosage and risk copy the category requires.",
    images: img("essential-oil-boxes"),
    featured: true,
  },

  // ── Food ──────────────────────────────────────────────────────────
  {
    slug: "coffee-box",
    client: "Coffee brand",
    clientType: "Café / Coffee",
    industry: "Food",
    packagingType: "Food Boxes",
    filters: ["Food", "Food Boxes", "Boxes"],
    product: "Coffee box",
    material: "Printed board",
    customization: ["Printed box", "Tuck-top closure", "Brand-colour design"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed retail-ready packaging for a 10-pod espresso pack.",
    outcome: "Clean printed box that works for retail and gifting.",
    images: img("coffee-box"),
    featured: true,
  },
  {
    slug: "coffee-variety-kit",
    client: "Coffee roaster",
    clientType: "Café / Coffee",
    industry: "Food",
    packagingType: "Food Boxes",
    filters: ["Food", "Food Boxes", "Boxes", "Gift"],
    product: "Coffee variety kit",
    material: "Printed board, sleeve & tray",
    customization: ["Printed sleeve", "Slide-out tray", "Per-blend panel design"],
    quantityRange: "1,000–5,000",
    problemSolved: "Wanted a sampler that explains four blends without a separate leaflet.",
    outcome: "Sleeve-and-tray kit where each blend gets its own panel and flavour scale.",
    images: img("coffee-variety-kit"),
  },
  {
    slug: "date-bar-box",
    client: "Snack brand",
    clientType: "Health Food",
    industry: "Food",
    packagingType: "Food Boxes",
    filters: ["Food", "Food Boxes", "Boxes"],
    product: "Date bar box",
    material: "Printed board",
    customization: ["Printed box", "Product photography", "Dietary icons"],
    quantityRange: "1,000–5,000",
    problemSolved: "A 6-pack of bars needed a box that shows the product and its dietary marks at a glance.",
    outcome: "Printed multipack carton with product shot, flavour and dietary icons on the face.",
    images: img("date-bar-box"),
  },
  {
    slug: "honey-box",
    client: "Supplement brand",
    clientType: "Health Food",
    industry: "Food",
    packagingType: "Food Boxes",
    filters: ["Food", "Food Boxes", "Boxes"],
    product: "Honey sachet box",
    material: "Printed board",
    customization: ["Printed box", "Gold foil accents", "Nutrition panel"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed a premium-feeling box for 16 sachets with a full nutrition panel.",
    outcome: "Dark printed carton with gold accents and the nutrition table on the side panel.",
    images: img("honey-box"),
  },

  // ── Fashion / retail ──────────────────────────────────────────────
  {
    slug: "souvenir-bag",
    client: "Development organisation",
    clientType: "Event / Institutional",
    industry: "Fashion",
    packagingType: "Paper Bags",
    filters: ["Fashion", "Paper Bags", "Retail", "Gift"],
    product: "Souvenir bag",
    material: "Art paper, laminated",
    customization: ["Printed bag", "Rope handles", "Matt lamination"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed a programme bag that looked considered enough to hand to delegates.",
    outcome: "Laminated rope-handle bag that carries a full-bleed design and holds its shape.",
    images: img("souvenir-bag"),
  },
  {
    slug: "jewelry-box",
    client: "Jewellery brand",
    clientType: "E-commerce / D2C",
    industry: "E-commerce",
    packagingType: "Boxes",
    filters: ["E-commerce", "Boxes", "Retail", "Fashion"],
    product: "Jewellery box",
    material: "Printed board",
    customization: ["Printed box", "Die-cut window", "Pastel panel design"],
    quantityRange: "500–1,000",
    problemSolved: "An online-first jewellery line needed the piece visible before the box is opened.",
    outcome: "Window box that shows the product on arrival and carries the shop URL on the face.",
    images: img("jewelry-box"),
    featured: true,
  },

  // ── Retail ────────────────────────────────────────────────────────
  {
    slug: "rigid-box",
    client: "Photography studio",
    clientType: "Creative Studio",
    industry: "Retail",
    packagingType: "Gift Boxes",
    filters: ["Retail", "Boxes", "Gift Boxes"],
    product: "Rigid box",
    material: "Rigid board, soft-touch wrap",
    customization: ["Rigid magnetic box", "Gold foil logo", "Soft-touch lamination"],
    quantityRange: "500–1,000",
    problemSolved: "Client deliverables needed a hand-over box that matched the studio's own brand.",
    outcome: "Soft-touch black magnetic box with a foiled logo, shot from four angles.",
    images: img("rigid-box"),
    featured: true,
  },
];
