import type { Project } from "./types";
import { productImages } from "./product-images";

// Portfolio grouped by ICP + packaging type (blueprint §12). Each project shows
// ALL photographed angles of that product via a left–right scrolling gallery.
// Client names are generic where not confirmed — replace before launch.

const img = (slug: string) => productImages[slug] ?? [];

export const projects: Project[] = [
  // ── Gift / corporate ──────────────────────────────────────────────
  {
    slug: "corporate-gift-box",
    client: "Corporate Client",
    clientType: "Corporate Gifting",
    industry: "Gift",
    packagingType: "Gift Boxes",
    filters: ["Gift", "Gift Boxes", "Boxes"],
    product: "Executive welcome / gift box",
    material: "Rigid board, magnetic closure",
    customization: ["Rigid magnetic box", "Custom insert", "Foil logo", "Soft-touch finish"],
    quantityRange: "300–500",
    problemSolved: "Wanted a memorable corporate gift that holds several items neatly.",
    outcome: "Premium magnetic gift box with a fitted insert, shot from every angle.",
    images: img("corporate-gift-box"),
    featured: true,
  },
  {
    slug: "discovery-box",
    client: "Beauty Brand",
    clientType: "Discovery / Sampling",
    industry: "Gift",
    packagingType: "Gift Boxes",
    filters: ["Gift", "Gift Boxes", "Cosmetics"],
    product: "Discovery / sampling box",
    material: "Printed rigid board",
    customization: ["Printed box", "Insert", "Branded sleeve"],
    quantityRange: "500–1,000",
    problemSolved: "Needed a compact discovery box for a sampling campaign.",
    outcome: "Neat discovery box that presents multiple samples cleanly.",
    images: img("discovery-box"),
  },
  {
    slug: "dawlance-kit",
    client: "Corporate Brand",
    clientType: "Corporate Gifting",
    industry: "Gift",
    packagingType: "Inserts & Cards",
    filters: ["Gift", "Inserts & Cards", "E-commerce"],
    product: "Branded gift kit",
    material: "Printed board & card",
    customization: ["Printed box", "Branded cards", "Insert"],
    quantityRange: "500–1,000",
    problemSolved: "Needed a branded kit that felt cohesive on unboxing.",
    outcome: "Matching box, insert and card set for a consistent brand moment.",
    images: img("dawlance-kit"),
  },

  // ── Cosmetics / fragrance ─────────────────────────────────────────
  {
    slug: "mist-boomerang-chic",
    client: "Fragrance Brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Boomerang Chic",
    material: "Printed board",
    customization: ["Printed box", "Brand-colour design"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed eye-catching retail boxes for a body-mist line.",
    outcome: "Bold printed mist box photographed from four angles.",
    images: img("mist-boomerang-chic"),
    featured: true,
  },
  {
    slug: "mist-blank-spell",
    client: "Fragrance Brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Blank Spell",
    material: "Printed board",
    customization: ["Printed box", "Matte lamination"],
    quantityRange: "1,000–5,000",
    problemSolved: "Wanted a premium feel across a mist range.",
    outcome: "Clean printed box consistent with the range.",
    images: img("mist-blank-spell"),
  },
  {
    slug: "mist-classical-rockstar",
    client: "Fragrance Brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Classical Rockstar",
    material: "Printed board",
    customization: ["Printed box", "Brand-colour design"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed shelf stand-out for a mist SKU.",
    outcome: "Distinct printed box shot from multiple angles.",
    images: img("mist-classical-rockstar"),
  },
  {
    slug: "mist-crooked-smile",
    client: "Fragrance Brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Crooked Smile",
    material: "Printed board",
    customization: ["Printed box", "Spot finish"],
    quantityRange: "1,000–5,000",
    problemSolved: "Wanted a playful, on-brand box.",
    outcome: "Characterful printed box across three views.",
    images: img("mist-crooked-smile"),
  },
  {
    slug: "mist-designer-crime",
    client: "Fragrance Brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Designer Crime",
    material: "Printed board",
    customization: ["Printed box"],
    quantityRange: "500–1,000",
    problemSolved: "Needed a cohesive box for a new scent.",
    outcome: "On-brand printed box, two angles.",
    images: img("mist-designer-crime"),
  },
  {
    slug: "mist-drop-beat",
    client: "Fragrance Brand",
    clientType: "Perfume / Mist",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Body mist — Drop Beat",
    material: "Printed board",
    customization: ["Printed box", "Brand-colour design"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed a vibrant box for a youth-oriented scent.",
    outcome: "Energetic printed box across three views.",
    images: img("mist-drop-beat"),
  },
  {
    slug: "perfume-kai",
    client: "Perfume House",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Gift Boxes",
    filters: ["Cosmetics", "Gift Boxes", "Boxes"],
    product: "Eau de parfum — Kai",
    material: "Rigid board, printed wrap",
    customization: ["Rigid box", "Foil logo"],
    quantityRange: "300–500",
    problemSolved: "Needed premium shelf presence for a fragrance.",
    outcome: "Rigid perfume box with box-and-bottle shots.",
    images: img("perfume-kai"),
    featured: true,
  },
  {
    slug: "perfume-mulan",
    client: "Perfume House",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Gift Boxes",
    filters: ["Cosmetics", "Gift Boxes", "Boxes"],
    product: "Eau de parfum — Mulan",
    material: "Rigid board, printed wrap",
    customization: ["Rigid box", "Emboss"],
    quantityRange: "300–500",
    problemSolved: "Wanted a luxury feel for a signature scent.",
    outcome: "Premium rigid perfume box, multiple views.",
    images: img("perfume-mulan"),
  },
  {
    slug: "perfume-dyar",
    client: "Perfume House",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Gift Boxes",
    filters: ["Cosmetics", "Gift Boxes", "Boxes"],
    product: "Eau de parfum — Dyar",
    material: "Rigid board, printed wrap",
    customization: ["Rigid box", "Foil logo"],
    quantityRange: "300–500",
    problemSolved: "Needed a premium box for a new fragrance.",
    outcome: "Clean rigid perfume box.",
    images: img("perfume-dyar"),
  },
  {
    slug: "perfume-ezra",
    client: "Perfume House",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Gift Boxes",
    filters: ["Cosmetics", "Gift Boxes", "Boxes"],
    product: "Eau de parfum — Ezra",
    material: "Rigid board, printed wrap",
    customization: ["Rigid box"],
    quantityRange: "300–500",
    problemSolved: "Wanted consistent premium packaging across scents.",
    outcome: "Rigid perfume box matched to the range.",
    images: img("perfume-ezra"),
  },
  {
    slug: "perfume-mumba",
    client: "Perfume House",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Gift Boxes",
    filters: ["Cosmetics", "Gift Boxes", "Boxes"],
    product: "Eau de parfum — Mumba",
    material: "Rigid board, printed wrap",
    customization: ["Rigid box", "Foil logo"],
    quantityRange: "300–500",
    problemSolved: "Needed a standout box for a hero scent.",
    outcome: "Bold rigid perfume box.",
    images: img("perfume-mumba"),
  },
  {
    slug: "perfume-zaram",
    client: "Perfume House",
    clientType: "Perfume / Fragrance",
    industry: "Cosmetics",
    packagingType: "Gift Boxes",
    filters: ["Cosmetics", "Gift Boxes", "Boxes"],
    product: "Eau de parfum — Zaram",
    material: "Rigid board, printed wrap",
    customization: ["Rigid box"],
    quantityRange: "300–500",
    problemSolved: "Wanted a refined box for a fragrance launch.",
    outcome: "Refined rigid perfume box.",
    images: img("perfume-zaram"),
  },
  {
    slug: "perfume-box",
    client: "Cosmetics Brand",
    clientType: "Cosmetics",
    industry: "Cosmetics",
    packagingType: "Boxes",
    filters: ["Cosmetics", "Boxes"],
    product: "Perfume product box",
    material: "Printed board",
    customization: ["Printed box", "Window"],
    quantityRange: "500–1,000",
    problemSolved: "Needed a clean retail box for a fragrance product.",
    outcome: "Simple, premium printed perfume box.",
    images: img("perfume-box"),
  },

  // ── Food ──────────────────────────────────────────────────────────
  {
    slug: "coffee-box",
    client: "Coffee Brand",
    clientType: "Café / Coffee",
    industry: "Food",
    packagingType: "Food Boxes",
    filters: ["Food", "Food Boxes", "Boxes"],
    product: "Espresso coffee pods",
    material: "Printed board",
    customization: ["Printed box", "Brand-colour design"],
    quantityRange: "1,000–5,000",
    problemSolved: "Needed retail-ready, practical coffee packaging.",
    outcome: "Clean printed box that works for retail and gifting.",
    images: img("coffee-box"),
    featured: true,
  },

  // ── Fashion / retail ──────────────────────────────────────────────
  {
    slug: "souvenir-bag",
    client: "Retail / Fashion Brand",
    clientType: "Fashion / Retail",
    industry: "Fashion",
    packagingType: "Paper Bags",
    filters: ["Fashion", "Paper Bags", "Retail"],
    product: "Retail shopping bag",
    material: "Art paper, laminated",
    customization: ["Printed bag", "Rope handles"],
    quantityRange: "1,000–5,000",
    problemSolved: "Current bags felt low-end and inconsistent.",
    outcome: "Premium branded shopping bag customers carry home.",
    images: img("souvenir-bag"),
  },

  // ── Retail / e-commerce boxes ─────────────────────────────────────
  {
    slug: "rigid-box",
    client: "Premium Retail Brand",
    clientType: "Retail",
    industry: "Retail",
    packagingType: "Boxes",
    filters: ["Retail", "Boxes", "Gift Boxes"],
    product: "Hero product box",
    material: "Rigid board, printed wrap",
    customization: ["Rigid box", "Emboss", "Lamination"],
    quantityRange: "500–1,000",
    problemSolved: "Needed a flagship box that lifts the whole range upmarket.",
    outcome: "Durable premium rigid box, four angles.",
    images: img("rigid-box"),
    featured: true,
  },
  {
    slug: "ecommerce-boxes",
    client: "Online Brand",
    clientType: "E-commerce / D2C",
    industry: "E-commerce",
    packagingType: "Boxes",
    filters: ["E-commerce", "Boxes"],
    product: "Mailer / product boxes",
    material: "Shipping-grade board",
    customization: ["Printed mailer", "Insert"],
    quantityRange: "500–1,000",
    problemSolved: "Orders arrived in plain boxes that felt unbranded.",
    outcome: "Branded product boxes that elevate unboxing, multiple views.",
    images: img("ecommerce-boxes"),
  },
  {
    slug: "product-boxes",
    client: "Product Brand",
    clientType: "Retail",
    industry: "Retail",
    packagingType: "Boxes",
    filters: ["Retail", "Boxes"],
    product: "Custom product boxes",
    material: "Printed board",
    customization: ["Printed box", "Die-cut"],
    quantityRange: "500–1,000",
    problemSolved: "Needed consistent boxes across a small product line.",
    outcome: "Consistent printed box system, several views.",
    images: img("product-boxes"),
  },
  {
    slug: "retail-boxes",
    client: "Retail Brand",
    clientType: "Retail",
    industry: "Retail",
    packagingType: "Boxes",
    filters: ["Retail", "Boxes"],
    product: "Retail box range",
    material: "Printed board",
    customization: ["Printed boxes", "Range-wide consistency"],
    quantityRange: "1,000–5,000",
    problemSolved: "Packaging looked inconsistent across the range.",
    outcome: "A unified shelf-ready box system, six views.",
    images: img("retail-boxes"),
  },
  {
    slug: "editorial-packaging",
    client: "Studio Showcase",
    clientType: "Packaging Studio",
    industry: "Retail",
    packagingType: "Boxes",
    filters: ["Retail", "Boxes", "Gift Boxes"],
    product: "Editorial packaging set",
    material: "Mixed board & finishes",
    customization: ["Printing", "Foil", "Emboss", "Rigid"],
    quantityRange: "Various",
    problemSolved: "A showcase of finishes and structures we produce.",
    outcome: "An editorial set spanning twelve packaging looks.",
    images: img("editorial-packaging"),
    featured: true,
  },
];
