// AUTO-GENERATED by scripts/prep-images.mjs — do not edit by hand.
// Maps a product slug to all of its image paths (gallery order).

export const productImages: Record<string, string[]> = {
  "perfume-kai": [
    "/images/products/perfume-kai/01.jpg",
    "/images/products/perfume-kai/02.jpg"
  ],
  "perfume-mulan": [
    "/images/products/perfume-mulan/01.jpg",
    "/images/products/perfume-mulan/02.jpg"
  ],
  "perfume-dyar": [
    "/images/products/perfume-dyar/01.jpg"
  ],
  "perfume-ezra": [
    "/images/products/perfume-ezra/01.jpg"
  ],
  "perfume-mumba": [
    "/images/products/perfume-mumba/01.jpg"
  ],
  "perfume-zaram": [
    "/images/products/perfume-zaram/01.jpg"
  ],
  "mist-boomerang-chic": [
    "/images/products/mist-boomerang-chic/01.jpg",
    "/images/products/mist-boomerang-chic/02.jpg",
    "/images/products/mist-boomerang-chic/03.jpg",
    "/images/products/mist-boomerang-chic/04.jpg"
  ],
  "mist-blank-spell": [
    "/images/products/mist-blank-spell/01.jpg",
    "/images/products/mist-blank-spell/02.jpg",
    "/images/products/mist-blank-spell/03.jpg"
  ],
  "mist-classical-rockstar": [
    "/images/products/mist-classical-rockstar/01.jpg",
    "/images/products/mist-classical-rockstar/02.jpg",
    "/images/products/mist-classical-rockstar/03.jpg"
  ],
  "mist-crooked-smile": [
    "/images/products/mist-crooked-smile/01.jpg",
    "/images/products/mist-crooked-smile/02.jpg",
    "/images/products/mist-crooked-smile/03.jpg"
  ],
  "mist-designer-crime": [
    "/images/products/mist-designer-crime/01.jpg",
    "/images/products/mist-designer-crime/02.jpg"
  ],
  "mist-drop-beat": [
    "/images/products/mist-drop-beat/01.jpg",
    "/images/products/mist-drop-beat/02.jpg",
    "/images/products/mist-drop-beat/03.jpg"
  ],
  "corporate-gift-box": [
    "/images/products/corporate-gift-box/01.jpg",
    "/images/products/corporate-gift-box/02.jpg",
    "/images/products/corporate-gift-box/03.jpg",
    "/images/products/corporate-gift-box/04.jpg",
    "/images/products/corporate-gift-box/05.jpg",
    "/images/products/corporate-gift-box/06.jpg",
    "/images/products/corporate-gift-box/07.jpg",
    "/images/products/corporate-gift-box/08.jpg",
    "/images/products/corporate-gift-box/09.jpg",
    "/images/products/corporate-gift-box/10.jpg",
    "/images/products/corporate-gift-box/11.jpg",
    "/images/products/corporate-gift-box/12.jpg"
  ],
  "discovery-box": [
    "/images/products/discovery-box/01.jpg",
    "/images/products/discovery-box/02.jpg",
    "/images/products/discovery-box/03.jpg"
  ],
  "dawlance-kit": [
    "/images/products/dawlance-kit/01.jpg",
    "/images/products/dawlance-kit/02.jpg"
  ],
  "rigid-box": [
    "/images/products/rigid-box/01.jpg",
    "/images/products/rigid-box/02.jpg",
    "/images/products/rigid-box/03.jpg",
    "/images/products/rigid-box/04.jpg"
  ],
  "coffee-box": [
    "/images/products/coffee-box/01.jpg"
  ],
  "perfume-box": [
    "/images/products/perfume-box/01.jpg"
  ],
  "souvenir-bag": [
    "/images/products/souvenir-bag/01.jpg"
  ],
  "ecommerce-boxes": [
    "/images/products/ecommerce-boxes/01.jpg",
    "/images/products/ecommerce-boxes/02.jpg",
    "/images/products/ecommerce-boxes/03.jpg",
    "/images/products/ecommerce-boxes/04.jpg"
  ],
  "product-boxes": [
    "/images/products/product-boxes/01.jpg",
    "/images/products/product-boxes/02.jpg",
    "/images/products/product-boxes/03.jpg",
    "/images/products/product-boxes/04.jpg"
  ],
  "retail-boxes": [
    "/images/products/retail-boxes/01.jpg",
    "/images/products/retail-boxes/02.jpg",
    "/images/products/retail-boxes/03.jpg",
    "/images/products/retail-boxes/04.jpg",
    "/images/products/retail-boxes/05.jpg",
    "/images/products/retail-boxes/06.jpg"
  ],
  "editorial-packaging": [
    "/images/products/editorial-packaging/01.jpg",
    "/images/products/editorial-packaging/02.jpg",
    "/images/products/editorial-packaging/03.jpg",
    "/images/products/editorial-packaging/04.jpg",
    "/images/products/editorial-packaging/05.jpg",
    "/images/products/editorial-packaging/06.jpg",
    "/images/products/editorial-packaging/07.jpg",
    "/images/products/editorial-packaging/08.jpg",
    "/images/products/editorial-packaging/09.jpg",
    "/images/products/editorial-packaging/10.jpg",
    "/images/products/editorial-packaging/11.jpg",
    "/images/products/editorial-packaging/12.jpg"
  ]
};
